 -- INSERT DEFAULT VALUES

INSERT INTO "Catalogue" ("key",                 "en-GB",                "da-DK") VALUES 
('MENU.OPTION.NEW_COLONY',                      'New', 'Ny'),
('MENU.OPTION.CONTINUE_COLONY',                 'Continue', 'Fortsæt'),
('MENU.OPTION.JOIN_COLONY',                     'Join', 'Detlag'),
('MENU.OPTION.TUTORIAL',                        'Tutorial', 'Tutorial'),
('MENU.OPTION.CREATE_COLONY',                   'Create Colony', 'Lav Ny Koloni'),
('MENU.PAGE_TITTLE.SELECT_COLONY',              'Select', 'Vælg En Koloni'),
('MENU.SUB_TITLE.NAME_COLONY',                  'Name Your Colony', 'Navngiv Din Koloni'),
('MENU.PAGE_TITLE.CREATE_COLONY',               'Create a new colony', 'Lav en ny koloni'),
('MENU.PAGE_TITLE.JOIN_COLONY',                 'Join Colony', 'Tilslut dig en koloni'),
('MENU.SUB_TITLE.NO_COLONIES_YET',              'No Colonies Yet', 'Ingen Kolonier Endnu'),
('MENU.SUB_TITLE.INSERT_CODE_HERE',             'Insert The Colony Code Here', 'Insæt Koloniens Kode her'),
('MENU.NAVIGATION.BACK',                        'Back', 'Tilbage'),
('MENU.NAVIGATION.CONTINUE',                    'Continue', 'Fortsæt'),
('MENU.NAVIGATION.CANCEL',                      'Cancel', 'Afbryd'),
('MENU.NAVIGATION.CONFIRM',                     'Confirm', 'Godkend'),
('DATA.UNNAMED.COLLECTION',                     'Unnamed Collection',   'Navneløs Gruppering'), 
('DATA.UNNAMED.COLONY',                         'Unnamed Colony',       'Navneløs Koloni'),
('DATA.UNNAMED.MINIGAME',                       'Unnamed Minigame',     'Navneløst Miniaturespil'),
('DATA.UNNAMED.LOCATION',                       'Unnamed Location',     'Navneløs Lokation'),
('DATA.UNNAMED.ACHIEVEMENT',                    'Unnamed Achievement',  'Navneløs Præstation'),
('DATA.UNVISITED.COLONY',                       'Colony not visited',  'Koloni ikke besøgt'),
('DATA.VISITED.COLONY_MINUTES',                 'minutes ago',  'minutter siden'),
('DATA.VISITED.COLONY_HOURS',                   'hours ago',  'timer siden'),
('DATA.VISITED.COLONY_DAYS',                    'days ago',  'dage siden'),
('UI.DESCRIPTION_MISSING',                      'Missing Description',  'Manglende Beskrivelse'),
('LOCATION.OUTER_WALLS.NAME',                   'Outer Walls', 'Ydre Mure'),
('LOCATION.OUTER_WALLS.DESCRIPTION',            'Defends the colony against everything from asteroids to space pirates', 'Beskytter kolonien imod alt fra asteroider til pirater fra rummet'),
('LOCATION.SPACE_PORT.NAME',                    'Spaceport', 'Rumhavn'),
('LOCATION.SPACE_PORT.DESCRIPTION',             'A vital piece of infrastructure which facilitates trade and tourism', 'Et meget vigtigt sted, der tillader handel og tourisme'),
('LOCATION.HOME.NAME',                          'Home', 'Hjem'),
('LOCATION.HOME.DESCRIPTION',                   'A place of comfort and relaxation. Your very own appartment.', 'Et sted at unde sig ro og mag. Din helt egen lejlighed.'),
('LOCATION.TOWN_HALL.NAME',                     'Town Hall', 'Rådhus'),
('LOCATION.TOWN_HALL.DESCRIPTION',              'The heart of the colony, where all important, political decisions are made.', 'Koloniens politisk-pulserende hjerte hvor de vigtige beslutninger bliver taget.'),
('LOCATION.SHIELD_GENERATOR.NAME',             'Shield Generators', 'Skjoldgeneratorer'),
('LOCATION.SHIELD_GENERATOR.DESCRIPTION',      'Powerful generators that create a protective shield around the colony', 'Kraftfulde generatorer der skaber et beskyttende skjold omkring kolonien'),
('LOCATION.AQUIFER_PLANT.NAME',                 'Aquifer Plant', 'Vandværk'),
('LOCATION.AQUIFER_PLANT.DESCRIPTION',          'Processes and purifies water for the colony to use', 'Behandler og renser vand til koloniens brug'),
('LOCATION.AGRICULTURE_CENTER.NAME',            'Agriculture Center', 'Landbrugscenter'),
('LOCATION.AGRICULTURE_CENTER.DESCRIPTION',     'A high-tech facility for growing food in the harsh environment', 'En højteknologisk facilitet til dyrkning af fødevarer i det barske miljø'),
('LOCATION.VEHICLE_STORAGE.NAME',               'Vehicle Storage', 'Køretøjsopbevaring'),
('LOCATION.VEHICLE_STORAGE.DESCRIPTION',        'A secure area for storing and maintaining various vehicles', 'Et sikkert område til opbevaring og vedligeholdelse af forskellige køretøjer'),
('LOCATION.CANTINA.NAME',                       'Cantina', 'Kantine'),
('LOCATION.CANTINA.DESCRIPTION',                'A popular gathering place for colonists to relax and socialize', 'Et populært samlingssted for kolonister til at slappe af og socialisere'),
('LOCATION.RADAR_DISH.NAME',                    'Radar Dish', 'Radarantenne'),
('LOCATION.RADAR_DISH.DESCRIPTION',             'A crucial communication hub for the colony', 'Et afgørende kommunikationsknudepunkt for kolonien'),
('LOCATION.MINING_FACILITY.NAME',               'Mining Facility', 'Minefacilitet'),
('LOCATION.MINING_FACILITY.DESCRIPTION',        'Extracts valuable resources from the surrounding area', 'Udvinder værdifulde ressourcer fra det omkringliggende område'),
('ACHIEVEMENT.TUTORIAL_COMPLETE.TITLE',         'Tutorial Complete', 'Undervisningstime Fuldført'),
('ACHIEVEMENT.TUTORIAL_COMPLETE.DESCRIPTION',   'You have braved the mighty obstacles of the tutorial - well done!', 'Du har trodset de uoverkommelige forhindringer i undervisningstimen - flot klaret!'),
('TUTORIAL.NAVIGATION_DEMO.DESCRIPTION',        'Write where you want to go, and press Enter', 'Skriv hvor du vil hen, og tryk Enter'),
('TUTORIAL.WELCOME.TITLE',                      'Welcome', 'Velkommen'),
('TUTORIAL.TRIAL.TITLE',                        'Your turn', 'Prøv selv'),
('TUTORIAL.NAVIGATION_TRIAL.DESCRIPTION',       'Walk by all locations, you can only walk on the paths', 'Gå til alle steder, du kan kun gå på stierne'),
('TUTORIAL.LOCATION_DEMO.DESCRIPTION',          'To enter a location, walk to it, and write Visit', 'For at besøge et sted, gå derhen, og skriv Besøg'),
('TUTORIAL.LOCATION_TRIAL.DESCRIPTION',         'Visit the Outer Walls', 'Besøg de Ydre Mure'),
('TUTORIAL.MULTPLAYER.DESCRIPTION',             'To have your friends come visit your colony, enter the Space Port', 'For at venner kan besøge din koloni, åben Rumhavnen'),
('TUTORIAL.COMPLETE.TITLE', 'TUTORIAL COMPLETE', 'TUTORIAL GENNEMFØRT'),
('COLONY.UI.LEAVE',                             'Leave Colony', 'Forlad Koloni'),
('COLONY.UI_BUTTON.JOIN',                             'Join', 'Deltag'),
('COLONY.UI_BUTTON.LEAVE',                             'Leave', 'Forlad'),
('COLONY.UI_BUTTON.OPEN',                             'Open', 'Åben'),
('ACTION_INPUT.WRITE_HERE',                     'Type here', 'Skriv her')
;

INSERT INTO "AvailableLanguages" ("id", "code", "icon", "commonName", "coverage") VALUES 
(1, 'en-GB', 1015, 'English', 100),
(2, 'da-DK', 1012, 'Dansk', 100),
(3, 'nb-NO', 1013, 'Norsk', 0),
(4, 'sv-SE', 1014, 'Svenska', 0),
(5, 'de-DE', 1016, 'Deutsch', 0),
(6, 'nl-NL', 1017, 'Nederlands', 0);